branchName: '${issue.number}-${issue.title}'

branches:
  - label: enhancement
    prefix: feature/    
  - label: feature
    prefix: feature/
  - label: bug
    prefix: bugfix/
  - label: '*'
    prefix: issues/
