# generate branch
name: Branch Management

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  issues:
    types: [assigned]
  issue_comment:
    types: [created]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  create_issue_branch_job:
    runs-on: ubuntu-latest
    steps:
    - name: Create Issue Branch
      uses: robvanderleek/create-issue-branch@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
